directory:
  project: '../demos/single'
  det_model: '../models/detection_model'
  pose_model: '../models/pose_model'
  dae_model: '../models/dae_model'


animal:
  n_tracks: 2
  bodyparts: ['head', 'leftear', 'rightear', 'neck', 
              'leftelbow', 'rightelbow', 'lefthand', 'righthand', 
              'spinemid', 'tailbase', 'leftknee', 'rightknee', 
              'leftfoot', 'rightfoot', 'tailmid', 'tailend']
  skip: []


calibration:
  n_cameras: 4
  board_size: [11, 8]
  board_square_side_length: 20 # mm
  fisheye: false


visualization:
  track_cmap: 'Set2'
  skeleton_cmap: 'hls'
  skeleton:
    - ['head', 'leftear', 'neck', 'rightear', 'head']
    - ['tailbase', 'tailmid', 'tailend']
    - ['neck', 'spinemid', 'tailbase']
    - ['lefthand', 'leftelbow', 'neck', 'rightelbow', 'righthand']
    - ['leftfoot', 'leftknee', 'tailbase', 'rightknee', 'rightfoot']
  room_dimensions: [660, 560, 800, 30]


threshold:
  bbox: 0.2
  iou: 0.8
  keypoint: 0.5
  

triangulation:
  user_define_axes: true
  dae_enable: true


optimization:
  do_optimize: true
  n_deriv_smooth: 2
  scale_smooth: 2
  scale_length: 2
  scale_length_weak: 1

  bodypart_distance:
    'head - rightear': 21.0 # mm
    'head - leftear': 21.0
    'rightear - neck': 52.0
    'leftear - neck': 52.0
    'neck - spinemid': 58.0
    'spinemid - tailbase': 73.0
    'neck - rightelbow': 73.0
    'rightelbow - righthand': 54.0
    'neck - leftelbow': 73.0
    'leftelbow - lefthand': 54.0
    'tailbase - rightknee': 90.0
    'tailbase - leftknee': 90.0

  bodypart_distance_weak:
    'tailbase - tailmid': 103.0
    'tailmid - tailend': 103.0
    'rightknee - rightfoot': 42.0
    'leftknee - leftfoot': 42.0
